import { useCallback, useEffect, useRef, useState } from "react";
import { Terminal } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import { getCurrentApiBase } from "@/lib/api";

export interface ApprovalState {
  id: string;
  command: string;
}

export interface TerminalStatus {
  connected: boolean;
  cwd: string | null;
  shell: string | null;
}

const WS_BASE = () => getCurrentApiBase().replace(/^http/, "ws");

// xterm 握手/内部生成的序列（非用户输入），过滤后不转发给后端，避免污染行级拦截状态：
//   \x1b[?1;2c  DA1 设备属性响应       \x1b[O / \x1b[I  焦点进入/离开事件
function isAutoGeneratedInput(data: string): boolean {
  if (data === "\x1b[O" || data === "\x1b[I") return true;
  if (/^\x1b\[\?1;[0-9]+c$/.test(data)) return true; // DA1 响应
  if (/^\x1b\[\?[0-9]+;[0-9]+;[0-9]+c$/.test(data)) return true; // DA2 响应
  return false;
}

interface UseTerminalOptions {
  containerRef: React.RefObject<HTMLDivElement | null>;
  cwd?: string | null;
  cols?: number;
  rows?: number;
  active?: boolean;
}

export function useTerminal({ containerRef, cwd, cols = 120, rows = 30, active = true }: UseTerminalOptions) {
  const termRef = useRef<Terminal | null>(null);
  const fitRef = useRef<FitAddon | null>(null);
  const wsRef = useRef<WebSocket | null>(null);
  const sessionIdRef = useRef<string | null>(null);
  const reconnectTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const closedRef = useRef(false);

  const [approval, setApproval] = useState<ApprovalState | null>(null);
  const [status, setStatus] = useState<TerminalStatus>({ connected: false, cwd: null, shell: null });

  // 无 sid 且需要指定 cwd 时，先走 POST 创建会话（携带 cwd），拿到 sid 再连 WS
  const ensureSession = useCallback(async (): Promise<string | null> => {
    if (sessionIdRef.current) return sessionIdRef.current;
    try {
      const res = await fetch(`${getCurrentApiBase()}/api/terminal`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ cwd: cwd || undefined, cols, rows }),
      });
      if (!res.ok) return null;
      const data = await res.json();
      sessionIdRef.current = data.session_id as string;
      return sessionIdRef.current;
    } catch {
      return null;
    }
  }, [cwd, cols, rows]);

  // 用 ref 持有 connect，避免 onclose 闭包自引用 TDZ / 过期闭包
  const connectRef = useRef<(() => void) | null>(null);

  const connect = useCallback(() => {
    if (closedRef.current) return;
    if (wsRef.current && (wsRef.current.readyState === WebSocket.OPEN || wsRef.current.readyState === WebSocket.CONNECTING)) {
      return;
    }

    const openWs = (sid: string | null) => {
      const query = new URLSearchParams();
      if (sid) query.set("sid", sid);
      let ws: WebSocket;
      try {
        ws = new WebSocket(`${WS_BASE()}/api/terminal/ws?${query.toString()}`);
      } catch {
        setStatus((s) => ({ ...s, connected: false }));
        return;
      }
      wsRef.current = ws;

      ws.onopen = () => {
        setStatus((s) => ({ ...s, connected: true }));
      };

      ws.onmessage = (ev) => {
        let msg: Record<string, unknown>;
        try {
          msg = JSON.parse(ev.data as string);
        } catch {
          return;
        }
        const type = msg.type as string;
        if (type === "output" && typeof msg.data === "string") {
          termRef.current?.write(msg.data);
        } else if (type === "approval") {
          setApproval({ id: String(msg.id), command: String(msg.command) });
        } else if (type === "ready") {
          sessionIdRef.current = String(msg.sid);
          setStatus((s) => ({ ...s, cwd: msg.cwd as string | null, shell: msg.shell as string | null }));
          requestAnimationFrame(() => {
            fitRef.current?.fit();
          });
        } else if (type === "exit") {
          termRef.current?.write("\r\n[进程已退出]");
        } else if (type === "error") {
          termRef.current?.write(`\r\n[${String(msg.message)}]`);
        }
      };

      ws.onclose = () => {
        setStatus((s) => ({ ...s, connected: false }));
        wsRef.current = null;
        if (!closedRef.current) {
          if (reconnectTimerRef.current) clearTimeout(reconnectTimerRef.current);
          reconnectTimerRef.current = setTimeout(() => connectRef.current?.(), 1500);
        }
      };
    };

    void (sessionIdRef.current ? Promise.resolve(sessionIdRef.current) : ensureSession()).then((sid) => {
      if (closedRef.current) return;
      openWs(sid);
    });
  }, [ensureSession]);

  // 同步最新 connect 到 ref（供 onclose 重连闭包调用；在 effect 中赋值避免 render 期写 ref）
  useEffect(() => {
    connectRef.current = connect;
  }, [connect]);

  const send = useCallback((payload: Record<string, unknown>) => {
    if (wsRef.current && wsRef.current.readyState === WebSocket.OPEN) {
      wsRef.current.send(JSON.stringify(payload));
    }
  }, []);

  const dispose = useCallback(() => {
    closedRef.current = true;
    if (reconnectTimerRef.current) clearTimeout(reconnectTimerRef.current);
    if (wsRef.current) {
      wsRef.current.close();
      wsRef.current = null;
    }
    termRef.current?.dispose();
    termRef.current = null;
    fitRef.current = null;
    setApproval(null);
  }, []);

  // 初始化 / 销毁
  useEffect(() => {
    const container = containerRef.current;
    if (!container || !active) return;
    closedRef.current = false;

    const term = new Terminal({
      cursorBlink: true,
      fontSize: 13,
      fontFamily: "Cascadia Code, Consolas, 'Courier New', monospace",
      theme: {
        background: "transparent",
        foreground: "#e5e7eb",
        cursor: "#93c5fd",
      },
      scrollback: 5000,
      convertEol: false,
    });
    const fit = new FitAddon();
    term.loadAddon(fit);
    termRef.current = term;
    fitRef.current = fit;

    term.open(container);
    try {
      fit.fit();
    } catch { /* 容器未就绪时忽略 */ }

    term.onData((data) => {
      if (isAutoGeneratedInput(data)) return;
      send({ type: "input", data });
    });

    connect();

    return () => {
      // 面板关闭时销毁 xterm + WS（会话保持在后端，重开重建）
      dispose();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [containerRef, active]);

  // cwd 变化时重建连接（会话起始目录变化）
  useEffect(() => {
    if (cwd) {
      sessionIdRef.current = null;
      if (wsRef.current) wsRef.current.close();
    }
  }, [cwd]);

  const resize = useCallback((w: number, h: number) => {
    send({ type: "resize", cols: w, rows: h });
  }, [send]);

  // 重新计算 xterm 本体渲染尺寸（FitAddon 自动算 cols/rows），再同步到后端。
  // 拖拽调宽 / 全屏切换时容器尺寸变化，调用本方法保证内容区实时跟手。
  const fitAndSync = useCallback(() => {
    const term = termRef.current;
    if (!term) return;
    try {
      fitRef.current?.fit();
    } catch {
      /* 容器过小时 FitAddon 可能抛错，忽略即可 */
    }
    send({ type: "resize", cols: term.cols, rows: term.rows });
  }, [send]);

  const approve = useCallback(() => {
    if (!approval) return;
    send({ type: "approve", id: approval.id });
    setApproval(null);
  }, [approval, send]);

  const reject = useCallback(() => {
    if (!approval) return;
    send({ type: "reject", id: approval.id });
    setApproval(null);
  }, [approval, send]);

  const closeSession = useCallback(() => {
    send({ type: "close" });
    if (wsRef.current) {
      wsRef.current.close();
      wsRef.current = null;
    }
    setStatus((s) => ({ ...s, connected: false }));
  }, [send]);

  const clear = useCallback(() => {
    termRef.current?.clear();
  }, []);

  return { send, resize, fitAndSync, approve, reject, closeSession, dispose, clear, approval, status };
}
